"""错题分析相关

Revision ID: 27c019f958fc
Revises: 0a3e7121bf5b
Create Date: 2025-12-23 12:25:56.864003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c019f958fc'
down_revision = '0a3e7121bf5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grading_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grading_results', schema=None) as batch_op:
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
