"""小测相关

Revision ID: 282d6276435c
Revises: 485f7f38a31e
Create Date: 2025-12-11 17:05:02.865280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282d6276435c'
down_revision = '485f7f38a31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_response', schema=None) as batch_op:
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
