"""生成习题相关

Revision ID: 2fa636c03176
Revises: 27c019f958fc
Create Date: 2025-12-28 17:06:51.051821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa636c03176'
down_revision = '27c019f958fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('response_time', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grading_results', schema=None) as batch_op:
        batch_op.drop_column('exercise_id')

    op.drop_table('exercise_response')
    op.drop_table('exercise_question')
    op.drop_table('exercise')
    # ### end Alembic commands ###
