"""first

Revision ID: ab79606b540f
Revises: 09b39d77144f
Create Date: 2025-11-13 01:19:41.073124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab79606b540f'
down_revision = '09b39d77144f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('file')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_attendance_course_id', 'course', ['course_id'], ['id'])

    with op.batch_alter_table('course_students', schema=None) as batch_op:
        batch_op.drop_column('finally_score')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('start_time')
        batch_op.drop_column('question')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('create_time')
        batch_op.drop_column('title')

    with op.batch_alter_table('course_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finally_score', sa.FLOAT(), server_default=sa.text("'0'"), nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_course_id', type_='foreignkey')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('tags')

    op.create_table('file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('mimetype', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_question')
    op.drop_table('students')
    # ### end Alembic commands ###
