"""信息

Revision ID: 754a5a5cdfeb
Revises: f4059b07ed3d
Create Date: 2025-03-21 22:13:19.542017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754a5a5cdfeb'
down_revision = 'f4059b07ed3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
