"""courseid

Revision ID: f3c90c3e5a3b
Revises: 0225e3766480
Create Date: 2025-03-20 15:36:24.282586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c90c3e5a3b'
down_revision = '0225e3766480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_assignment_course_id', 'course', ['course_id'], ['id'])

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignment_course_id', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###